CREATE TABLE PDF (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME           TEXT    NOT NULL,
  HASH           TEXT    NOT NULL,
  DATE           INT     NOT NULL,
  TITLE          TEXT    NOT NULL,
  AUTHORS        TEXT    NOT NULL,
  DEPARTMENT     TEXT,
  COLLEGE        TEXT,
  CAMPUS         TEXT,
  ABSTRACT       TEXT,
  INDEX_TERMS    TEXT,
  YEAR           TEXT    NOT NULL,
  MONTH          TEXT    NOT NULL,
  UPLOADED_BY    TEXT,
  CREATED_AT     DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE FREQ (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  PDF_ID         INT     NOT NULL,
  WORD           TEXT    NOT NULL,
  W_FREQ         REAL    NOT NULL
);
